version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
  deploy-prod:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "./deploy.sh"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-prod:
          filters:
            branches:
              only:
                - master
          requires:
            - build